const STORAGE_KEY="grow-data-v1";
const app=document.getElementById("app");
const types={weekly:"Hebdomadaire",entry:"Entrée","day-after":"Lendemain de l’entrée",team:"Décision d’équipe",other:"Autre"};
let data=load();
let activeId=data.activeId||null;
let view=activeId?"dashboard":"stays";
let editingId=null;
let chartMode="hospital";

function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{stays:[]}}catch{return{stays:[]}}}
function save(){data.activeId=activeId;localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function n(value){return Number(String(value||"").replace(",","."))}
function fmt(value,d=1){return Number(value).toLocaleString("fr-FR",{minimumFractionDigits:d,maximumFractionDigits:d})}
function signed(value){return `${value>0?"+":value<0?"−":""}${fmt(Math.abs(value))} kg`}
function days(a,b){return Math.max(0,Math.round((new Date(b)-new Date(a))/86400000))}
function bmi(w,h){return w/((h/100)**2)}
function ordered(stay){return [...stay.weighings].sort((a,b)=>a.date.localeCompare(b.date))}
function currentStay(){return data.stays.find(s=>s.id===activeId)||null}
function status(delta,grams){return delta*1000>=grams?"Prise significative":delta*1000<=-grams?"Perte significative":"Stable"}
function dateFR(value,short=false){return new Date(value+"T12:00:00").toLocaleDateString("fr-FR",short?{day:"2-digit",month:"2-digit"}:undefined)}
function ageYears(month,date){return(new Date(date+"T12:00:00")-new Date(month+"-15T12:00:00"))/31557600000}

function shell(content,nav=true){return `<div class="ambient ambient-one"></div><div class="ambient ambient-two"></div><div class="app-frame"><header class="topbar"><button class="brand" data-view="stays"><span class="brand-mark">⌁</span><span>Grow</span></button><button class="round-button" data-view="settings" aria-label="Réglages" ${activeId?"":"disabled"}>⌕</button></header>${content}${nav&&activeId?navHtml():""}</div>${activeId?printHtml(currentStay()):""}`}
function navHtml(){return `<nav class="tabbar"><button data-view="stays"><span>⌂</span>Séjours</button><button data-view="dashboard" class="${view==="dashboard"?"active":""}"><span>◉</span>Situation</button><button class="add-button" data-view="add">＋</button><button data-view="charts" class="${view==="charts"?"active":""}"><span>⌁</span>Courbes</button><button data-view="table" class="${view==="table"?"active":""}"><span>▦</span>Tableau</button></nav>`}

function render(){
  const stay=currentStay();
  let content="";
  if(view==="stays")content=staysHtml();
  else if(view==="create")content=createHtml();
  else if(!stay){view="stays";content=staysHtml()}
  else if(view==="dashboard")content=dashboardHtml(stay);
  else if(view==="add")content=weighingHtml(stay);
  else if(view==="table")content=tableHtml(stay);
  else if(view==="charts")content=chartsHtml(stay);
  else if(view==="settings")content=settingsHtml(stay);
  app.innerHTML=shell(content,!['stays','create'].includes(view));
  bind();
}

function staysHtml(){const active=data.stays.filter(s=>!s.closed),arch=data.stays.filter(s=>s.closed);return `<section class="page"><div class="eyebrow">${new Date().toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"})}</div><h1>Les séjours.</h1><p class="intro">Une vue simple de chaque trajectoire en cours.</p><div class="section-head"><h2>En cours</h2><button class="primary" data-view="create">Nouveau séjour</button></div>${active.length?`<div class="stay-list">${active.map(stayCard).join("")}</div>`:`<div class="empty"><span>⌁</span><h2>Aucun séjour en cours</h2><p>Crée le premier séjour pour commencer.</p></div>`}${arch.length?`<div class="section-head archived-title"><h2>Archives</h2></div><div class="stay-list">${arch.map(stayCard).join("")}</div>`:""}</section>`}
function stayCard(s,i=0){return `<button class="stay-card ${s.closed?"archived":""}" data-stay="${s.id}"><span class="stay-icon icon-${i%3}">⌁</span><span><b>${esc(s.label)}</b><small>Entrée le ${dateFR(s.entryDate)}</small></span><strong>›</strong></button>`}
function createHtml(){return `<section class="page form-page"><div class="eyebrow">Nouveau séjour</div><h1>Les repères de départ</h1><form id="create-form"><label>Identifiant non nominatif<input name="label" required placeholder="Séjour 22 · 07/2026"></label><div class="two"><label>Mois de naissance<input name="birthMonth" type="month" required></label><label>Sexe de la courbe<select name="sex"><option value="female">Féminin</option><option value="male">Masculin</option></select></label></div><div class="two"><label>Date d’entrée<input name="entryDate" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Taille (cm)<input name="height" type="number" step="0.1" required></label></div><div class="two"><label>Poids d’entrée (kg)<input name="entryWeight" type="number" step="0.1" required></label><label>Sortie de séparation (kg)<input name="separationWeight" type="number" step="0.1" required></label></div><label>Sortie d’hospitalisation (kg)<input name="dischargeWeight" type="number" step="0.1" required></label><button class="save">Créer le séjour</button></form></section>`}

function dashboardHtml(s){const list=ordered(s),cur=list.at(-1),prev=list.at(-2),week=[...list].slice(0,-1).reverse().find(w=>w.type==="weekly"),cw=cur.weight,next=cw<s.separationWeight?s.separationWeight:s.dischargeWeight,nextLabel=next===s.separationWeight?"Sortie de séparation":"Sortie d’hospitalisation",delta=prev?cw-prev.weight:0,weeklyDelta=week?cw-week.weight:cw-s.entryWeight;return `<section class="page"><div class="eyebrow">${esc(s.label)}</div><div class="dashboard-title"><div><h1>${fmt(cw)} kg</h1><p class="intro">Pesée du ${dateFR(cur.date)} · ${days(s.entryDate,cur.date)} jours d’hospitalisation</p></div><button class="small-add" data-view="add">＋ Pesée</button></div><div class="hero-grid"><article class="metric terracotta"><span>Dernière pesée</span><strong>${prev?signed(delta):"—"}</strong><small>${prev?`En ${days(prev.date,cur.date)} jours · ${status(delta,s.significantGrams).toLowerCase()}`:"Première mesure"}</small></article><article class="metric blue"><span>Prochain objectif</span><strong>${fmt(next)} kg</strong><small>${nextLabel} · reste ${fmt(Math.max(0,next-cw))} kg</small></article></div><div class="support-grid"><article class="glass"><small>Hebdomadaire</small><b>${signed(weeklyDelta)}</b><span class="tag">${status(weeklyDelta,s.significantGrams)}</span></article><article class="glass"><small>Depuis l’entrée</small><b>${signed(cw-s.entryWeight)}</b><span class="tag">Entrée : ${fmt(s.entryWeight)} kg</span></article></div><article class="glass thresholds">${threshold("IMC actuel",`Taille : ${fmt(cur.height)} cm`,fmt(bmi(cw,cur.height)))}${goalThreshold(s,list,s.separationWeight,"Sortie de séparation")}${goalThreshold(s,list,s.dischargeWeight,"Sortie d’hospitalisation")}</article></section>`}
function threshold(label,detail,value){return `<div class="threshold"><span><b>${label}</b><small>${detail}</small></span><em>${value}</em></div>`}
function goalThreshold(s,list,goal,label){const hit=list.find(w=>w.weight>=goal),cur=list.at(-1);return threshold(label,hit?`Atteint le ${dateFR(hit.date)}`:`Objectif : ${fmt(goal)} kg`,signed(cur.weight-goal))}

function weighingHtml(s){const list=ordered(s),item=editingId?list.find(w=>w.id===editingId):null,last=list.at(-1),today=new Date().toISOString().slice(0,10),weekly=new Date(today+"T12:00:00").getDay()===s.weeklyDay;return `<section class="page form-page"><div class="eyebrow">${item?"Modifier la mesure":"Nouvelle mesure"}</div><h1>${item?"Corriger une pesée":"Ajouter une pesée"}</h1><p class="intro">Tous les calculs seront mis à jour automatiquement.</p><form id="weighing-form"><label class="weight-input"><input name="weight" type="number" step="0.1" value="${item?.weight??""}" required><span>kg</span></label><div class="two"><label>Date<input name="date" type="date" value="${item?.date??today}" required></label><label>Taille (cm)<input name="height" type="number" step="0.1" value="${item?.height??last?.height??s.referenceHeight}" required></label></div><label>Type de pesée<select name="type">${Object.entries(types).map(([v,l])=>`<option value="${v}" ${(item?.type??(weekly?"weekly":"other"))===v?"selected":""}>${l}</option>`).join("")}</select></label><button class="save">${item?"Enregistrer les modifications":"Enregistrer la pesée"}</button>${item&&item.type!=="entry"?`<button class="delete" type="button" id="delete-weighing">Supprimer cette pesée</button>`:""}</form></section>`}

function tableHtml(s){const list=ordered(s);return `<section class="page"><div class="eyebrow">${esc(s.label)}</div><h1>Tableau</h1><p class="intro">Appuie sur une ligne pour modifier une pesée.</p><button class="export-button" id="export-pdf">Aperçu et export PDF · 3 pages</button><div class="table-wrap">${tableMarkup(s,list,true)}</div></section>`}
function tableMarkup(s,list,clickable=false){return `<table><thead><tr><th>Date</th><th>Type</th><th>Poids</th><th>Δ préc.</th><th>Δ hebdo.</th><th>IMC</th></tr></thead><tbody>${[...list].reverse().map(w=>{const i=list.findIndex(x=>x.id===w.id),prev=i?list[i-1]:null,week=[...list].slice(0,i).reverse().find(x=>x.type==="weekly");return `<tr ${clickable?`data-edit="${w.id}"`:""}><td>${dateFR(w.date,true)}</td><td>${types[w.type]}</td><td>${fmt(w.weight)}</td><td>${prev?signed(w.weight-prev.weight):"—"}</td><td>${week?signed(w.weight-week.weight):"—"}</td><td>${fmt(bmi(w.weight,w.height))}</td></tr>`}).join("")}</tbody></table>`}

function chartsHtml(s){return `<section class="page"><div class="eyebrow">${esc(s.label)}</div><h1>Courbes</h1><p class="intro">L’évolution pendant l’hospitalisation et la référence française.</p><div class="segmented"><button data-chart="hospital" class="${chartMode==="hospital"?"selected":""}">Hospitalisation</button><button data-chart="growth" class="${chartMode==="growth"?"selected":""}">Poids–Taille</button></div>${chartMode==="hospital"?hospitalChart(s):growthChart(s)}</section>`}
function hospitalChart(s,print=false){const list=ordered(s),values=list.map(w=>w.weight).concat([s.separationWeight,s.dischargeWeight]),min=Math.floor(Math.min(...values)-1),max=Math.ceil(Math.max(...values)+1),first=new Date(list[0].date),last=new Date(list.at(-1).date),x=d=>48+((new Date(d)-first)/Math.max(86400000,last-first))*584,y=w=>300-((w-min)/(max-min))*240,points=list.map(w=>`${x(w.date)},${y(w.weight)}`).join(" ");return `<div class="${print?"print-chart":"chart-card"}"><div class="chart-heading"><strong>Poids pendant l’hospitalisation</strong><small>${fmt(list[0].weight)} → ${fmt(list.at(-1).weight)} kg</small></div><svg viewBox="0 0 680 350">${[0,1,2,3,4].map(i=>`<line x1="48" x2="632" y1="${60+i*60}" y2="${60+i*60}" class="gridline"/>`).join("")}<line x1="48" x2="632" y1="${y(s.dischargeWeight)}" y2="${y(s.dischargeWeight)}" class="goal discharge"/><line x1="48" x2="632" y1="${y(s.separationWeight)}" y2="${y(s.separationWeight)}" class="goal separation"/><text x="628" y="${y(s.dischargeWeight)-7}" text-anchor="end">Sortie ${fmt(s.dischargeWeight)} kg</text><text x="628" y="${y(s.separationWeight)-7}" text-anchor="end">Séparation ${fmt(s.separationWeight)} kg</text><polyline points="${points}" class="data-line"/>${list.map(w=>w.type==="weekly"?`<circle cx="${x(w.date)}" cy="${y(w.weight)}" r="7" class="weekly-point"/>`:`<rect x="${x(w.date)-6}" y="${y(w.weight)-6}" width="12" height="12" rx="2" class="exception-point"/>`).join("")}<text x="48" y="332">${dateFR(list[0].date)}</text><text x="632" y="332" text-anchor="end">${dateFR(list.at(-1).date)}</text></svg><div class="legend"><span><i></i>Hebdomadaire</span><span><i class="square"></i>Exceptionnelle</span></div></div>`}
function growthChart(s,print=false){const list=ordered(s),src=s.sex==="female"?"public/courbe-filles.png":"public/courbe-garcons.png";return `<div class="${print?"growth-print":"growth-card"}"><div class="chart-heading"><strong>Courbe française Poids–Taille</strong><small>${s.sex==="female"?"Fille":"Garçon"} · AFPA–CRESS/Inserm 2018</small></div><div class="official-chart"><img src="${src}" alt="Courbe officielle">${list.map(w=>growthPoint(s,w,"height")).join("")}${list.map(w=>growthPoint(s,w,"weight")).join("")}</div></div>`}
function growthPoint(s,w,kind){const age=ageYears(s.birthMonth,w.date),left=10+((age-1)/17)*71.85;let top;if(kind==="height"){const max=s.sex==="female"?200:210,yt=3.7,yb=s.sex==="female"?67.2:71.5;top=yt+((max-w.height)/(max-60))*(yb-yt)}else top=35.3+((120-w.weight)/120)*54.7;return `<span class="growth-point ${kind}" style="left:${left}%;top:${top}%"></span>`}

function settingsHtml(s){return `<section class="page form-page"><div class="eyebrow">Grow</div><h1>Réglages</h1><p class="intro">Les paramètres du séjour et du contrat.</p><form id="settings-form"><label>Identifiant<input name="label" value="${esc(s.label)}" required></label><div class="two"><label>Mois de naissance<input name="birthMonth" type="month" value="${s.birthMonth}" required></label><label>Sexe<select name="sex"><option value="female" ${s.sex==="female"?"selected":""}>Féminin</option><option value="male" ${s.sex==="male"?"selected":""}>Masculin</option></select></label></div><div class="two"><label>Date d’entrée<input name="entryDate" type="date" value="${s.entryDate}" required></label><label>Taille (cm)<input name="height" type="number" step="0.1" value="${s.referenceHeight}" required></label></div><div class="two"><label>Poids d’entrée<input name="entryWeight" type="number" step="0.1" value="${s.entryWeight}" required></label><label>Sortie de séparation<input name="separationWeight" type="number" step="0.1" value="${s.separationWeight}" required></label></div><label>Sortie d’hospitalisation<input name="dischargeWeight" type="number" step="0.1" value="${s.dischargeWeight}" required></label><div class="two"><label>Jour hebdomadaire<select name="weeklyDay">${[[1,"Lundi"],[2,"Mardi"],[3,"Mercredi"],[4,"Jeudi"],[5,"Vendredi"]].map(([v,l])=>`<option value="${v}" ${s.weeklyDay==v?"selected":""}>${l}</option>`).join("")}</select></label><label>Variation significative<select name="significantGrams"><option value="500">± 500 g</option><option value="400">± 400 g</option><option value="600">± 600 g</option></select></label></div><button class="save">Enregistrer</button><button type="button" class="secondary" id="close-stay">${s.closed?"Rouvrir":"Clôturer"} le séjour</button><button type="button" class="delete" id="delete-stay">Supprimer le séjour</button></form></section>`}

function printHtml(s){if(!s)return"";const list=ordered(s);return `<div class="print-document"><section class="print-page portrait">${printHeader(s,"1/3")}<h1>Tableau des pesées</h1>${tableMarkup(s,list)}</section><section class="print-page portrait">${printHeader(s,"2/3")}${growthChart(s,true)}</section><section class="print-page landscape">${printHeader(s,"3/3")}${hospitalChart(s,true)}</section></div>`}
function printHeader(s,page){return `<header class="print-header"><div><b>Grow</b><span>${esc(s.label)}</span></div><small>Entrée le ${dateFR(s.entryDate)} · ${page}</small></header>`}

function bind(){
  document.querySelectorAll("[data-view]").forEach(el=>el.onclick=()=>{editingId=null;view=el.dataset.view;render()});
  document.querySelectorAll("[data-stay]").forEach(el=>el.onclick=()=>{activeId=el.dataset.stay;view="dashboard";save();render()});
  document.querySelectorAll("[data-edit]").forEach(el=>el.onclick=()=>{editingId=el.dataset.edit;view="add";render()});
  document.querySelectorAll("[data-chart]").forEach(el=>el.onclick=()=>{chartMode=el.dataset.chart;render()});
  const create=document.getElementById("create-form");if(create)create.onsubmit=e=>{e.preventDefault();const f=new FormData(create),id=uid(),entryDate=f.get("entryDate"),entryWeight=n(f.get("entryWeight")),height=n(f.get("height"));const s={id,label:f.get("label"),birthMonth:f.get("birthMonth"),sex:f.get("sex"),entryDate,entryWeight,referenceHeight:height,separationWeight:n(f.get("separationWeight")),dischargeWeight:n(f.get("dischargeWeight")),weeklyDay:3,significantGrams:500,closed:false,weighings:[{id:id+"-entry",date:entryDate,weight:entryWeight,height,type:"entry"}]};data.stays.push(s);activeId=id;view="dashboard";save();render()};
  const wf=document.getElementById("weighing-form");if(wf)wf.onsubmit=e=>{e.preventDefault();const s=currentStay(),f=new FormData(wf),item={id:editingId||uid(),date:f.get("date"),weight:n(f.get("weight")),height:n(f.get("height")),type:f.get("type")};s.weighings=editingId?s.weighings.map(w=>w.id===editingId?item:w):[...s.weighings,item];editingId=null;view="dashboard";save();render()};
  const delW=document.getElementById("delete-weighing");if(delW)delW.onclick=()=>{if(confirm("Supprimer cette pesée ?")){const s=currentStay();s.weighings=s.weighings.filter(w=>w.id!==editingId);editingId=null;view="table";save();render()}};
  const sf=document.getElementById("settings-form");if(sf)sf.onsubmit=e=>{e.preventDefault();const s=currentStay(),f=new FormData(sf),entryWeight=n(f.get("entryWeight")),height=n(f.get("height"));Object.assign(s,{label:f.get("label"),birthMonth:f.get("birthMonth"),sex:f.get("sex"),entryDate:f.get("entryDate"),entryWeight,referenceHeight:height,separationWeight:n(f.get("separationWeight")),dischargeWeight:n(f.get("dischargeWeight")),weeklyDay:n(f.get("weeklyDay")),significantGrams:n(f.get("significantGrams"))});s.weighings=s.weighings.map(w=>w.type==="entry"?{...w,date:s.entryDate,weight:entryWeight,height}:w);view="dashboard";save();render()};
  const close=document.getElementById("close-stay");if(close)close.onclick=()=>{const s=currentStay();s.closed=!s.closed;save();render()};
  const del=document.getElementById("delete-stay");if(del)del.onclick=()=>{if(confirm("Supprimer définitivement ce séjour ?")){data.stays=data.stays.filter(s=>s.id!==activeId);activeId=null;view="stays";save();render()}};
  const exp=document.getElementById("export-pdf");if(exp)exp.onclick=()=>window.print();
}

if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js").catch(()=>{});
render();
